compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  a:
    npmRegistryServer: "https://codeberg.org/api/packages/libselfisekai/npm/"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
