steps:
  test:
    when:
      event: [push, pull_request]
    image: rust:1.93-alpine3.23
    environment:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-Ctarget-feature=-crt-static"
    commands:
      - cargo check
      - cargo test
