# SPDX-FileCopyrightText: 2024 The Chaste Authors
# SPDX-License-Identifier: CC0-1.0

[workspace]
resolver = "2"
members = ["chaste", "chaste-npm", "chaste-types", "chaste-yarn"]

[workspace.package]
version = "0.1.0"
authors = ["The Chaste Authors"]
license = "Apache-2.0 OR BSD-2-Clause"
categories = ["parser-implementations", "data-structures"]
repository = "https://codeberg.org/selfisekai/chaste"

[workspace.dependencies]
chaste-npm = { version = "=0.1.0", path = "chaste-npm" }
chaste-types = { version = "=0.1.0", path = "chaste-types" }
chaste-yarn = { version = "=0.1.0", path = "chaste-yarn" }
logos = "0.14.2"
miette = "7"
nodejs-semver = "4.1.0"
nom = "7.1.3"
serde = "1.0.185"
serde_json = "1.0"
ssri = { version = "9.2", default-features = false }
thiserror = "2.0"
yarn-lock-parser = "0.9.0"

# FIXME: https://github.com/robertohuertasm/yarn-lock-parser/pull/24
[patch.crates-io]
yarn-lock-parser = { git = "https://github.com/selfisekai/yarn-lock-parser.git", rev = "b73e62df201a4bf95e870ba7436537bd68a470b7" }
