# SPDX-FileCopyrightText: 2024 The Chaste Authors
# SPDX-License-Identifier: CC0-1.0

[workspace]
resolver = "2"
members = ["chaste", "chaste-npm", "chaste-types", "chaste-yarn"]

[workspace.package]
version = "0.1.0"
authors = ["The Chaste Authors"]
license = "Apache-2.0 OR BSD-2-Clause"

[workspace.dependencies]
chaste-npm = { version = "=0.1.0", path = "chaste-npm" }
chaste-types = { version = "=0.1.0", path = "chaste-types" }
chaste-yarn = { version = "=0.1.0", path = "chaste-yarn" }
logos = "0.14.2"
nodejs-semver = "4.1.0"
serde = "1.0.185"
serde_json = "1.0"
thiserror = "2.0"
yarn-lock-parser = "0.7.0"

# FIXME: Submitted to upstream at:
#   - https://github.com/robertohuertasm/yarn-lock-parser/pull/20
#   - https://github.com/robertohuertasm/yarn-lock-parser/pull/21
[patch.crates-io.yarn-lock-parser]
git = "https://github.com/selfisekai/yarn-lock-parser.git"
branch = "chaste-dev"
