approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  a:
    npmRegistryServer: "https://s.lnl.gay/"

yarnPath: .yarn/releases/yarn-4.15.0.cjs
