# SPDX-FileCopyrightText: 2026 The Chaste Authors
# SPDX-License-Identifier: CC0-1.0

steps:
  test:
    when:
      event: [push, pull_request]
    image: rust:1.93-trixie
    environment:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-Ctarget-feature=-crt-static"
    commands:
      - cargo check --locked
      - cargo build --bin chaste --locked
      - cargo test --locked
